/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.morozov.xml;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.xml.stream.XMLStreamException;

public class Lab1 {

    public static void main(String[] args) {

        try (InputStream stream = new FileInputStream("app\\src\\main\\resources\\people.xml")) {
            new PeopleData().parse(stream);
        } catch (IOException | XMLStreamException e) {
            e.printStackTrace();
        }

    }
}
